config/routes.rb
Rails.application.routes.draw do
  root 'base_pages#home'
  get '/help', to: 'base_pages#help'
  get '/about', to: 'base_pages#about'
  get '/', to: 'base_pages#home'
  get  '/thepiss', to: 'base_pages#findthepiss', as: :show_the_piss
  post '/thepiss', to: 'base_pages#findthepiss', as: :find_the_piss
end

app/models/application_record.rb
# ApplicationRecord model
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
require 'rubygems'
require 'nokogiri'
require 'open-uri'

# Entry model
class Entry
  attr_reader :id
  attr_reader :title
  attr_reader :link
  attr_reader :summary
  attr_reader :source

  def initialize(title, link, summary, source)
    @title = title
    @link = link
    @summary = summary
    @source = source
  end

  def self.scrape(count, source)
    scrape_atts = ScrapeAttribute.find_by(source: source)
    doc = Nokogiri::HTML(open(scrape_atts[:url]))

    entries = doc.css(scrape_atts[:doc_split])
    entries_array = []
    entries[0, count.to_i].each do |entry|
      title = entry.css(scrape_atts[:title_split]).text
      link_base = entry.css(scrape_atts[:title_split])[0]['href'].to_s.gsub(scrape_atts[:link_sub], '')
      link_len = scrape_atts[:index_char].nil? ? link_base.length : link_base.index(scrape_atts[:index_char])
      link = link_base[0, link_len]
      summary = source == 'Vox' ? Summary.scrape(link, source) : entry.css(scrape_atts[:sum_split]).text

      entries_array << Entry.new(title, link, summary, source)
    end
    entries_array
  end
end

class Summary
  attr_reader :summary

  def initialize(summary)
    @summary = summary
  end

  def self.scrape(link, source)
    doc = Nokogiri::HTML(open(link))
    scrape_atts = ScrapeAttribute.find_by(source: source)
    entries = doc.css(scrape_atts[:sub_entry])
    @summary = entries.css(scrape_atts[:sub_summary]).text

    @summary
  end
end

app/models/scrape_attribute.rb
# ScrapeAttribute model
class ScrapeAttribute < ApplicationRecord
end

app/controllers/application_controller.rb
# Class for ApplicationController
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/base_pages_controller.rb
# Controller for the base pages of the app
class BasePagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def findthepiss
    @entries_array = []
    tinkle_source.each do |ts|
      @entries_array += Entry.scrape(tinkle_count, ts)
    end
    @entries_array.shuffle! # randomize the results
    @entries_array = @entries_array[0..(tinkle_count.to_i - 1)]
  end

  def displaythepiss; end

  private

  def tinkle_count
    return 10 if params[:search][:storycount].nil?
    params[:search][:storycount]
  end

  def tinkle_source
    params[:search][:storyloca].reject!(&:empty?)
  end

  # require/permit params here
end

app/helpers/application_helper.rb
# Helper for the entire application
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = 'Piss Finder'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/base_pages_helper.rb
# Helper for base pages only
module BasePagesHelper
end

app/views/base_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | <%= yield(:app_name) %></title>
  </head>
  <body>
    <h1>About page</h1>
</html>

app/views/base_pages/findthepiss.html.erb
<% provide(:title, "The Piss!") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | <%= yield(:app_name) %></title>
  </head>
  <body>
    <h1>Found the <%= pluralize(params[:search][:storycount], 'tinkle') %> you requested:</h1>
     <% @entries_array.each_with_index do |entry, i| %>
      <h5 class="link-text">(<%= (i + 1) %>) <a href="<%= entry.link %>" target="_blank"><%= entry.title %></a></h5>
      <div class="summary-text"><%= entry.summary %></div>
      <h6>--<%= entry.source %></h6><br>
    <% end %>
  </body>
</html>

app/views/base_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | <%= yield(:app_name) %></title>
  </head>
  <body>
    <h1>Help page</h1>
  </body>
</html>

app/views/base_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | <%= yield(:app_name) %></title>
  </head>
  <body>
    <h1>Find The Piss Below!</h1>
    <h2>
      This is the home page for the Donald Trump Piss Finder - your source for updates regarding the (alleged) Donald Trump <a href = "https://rationalwiki.org/wiki/Pissgate" target="_blank">piss tape.</a>
    </h2>
    <h5><p>How many donald trump pee tape stories do you want to read today?
      <%= simple_form_for :search, url: find_the_piss_path do |f| %>
        <%= f.select :storycount, ((1..30).map {|i| [i,i] }) %></p>
        <p>And from where will you read these stories about piss?
        <%= f.input :storyloca, label: false, as: :check_boxes, collection: ScrapeAttribute.pluck(:source) %>
        </p>
        <%= f.button :submit, "Submit" %>
      <% end %>
  </body>
</html>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Piss-Finder | Zero rights reserved.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Piss Finder", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path, :class => "ui-nav-link" %></li>
        <li><%= link_to "Help",   help_path, :class => "ui-nav-link" %></li>
        <li><%= link_to "About",   about_path, :class => "ui-nav-link" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
        <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>